// Generated by scripts/audio/build.mjs: do not edit. The files in apps/web/public/audio, each as
// .ogg (Opus) and .m4a (AAC). seconds is the length the build wrote: loops repeat over exactly that
// (AAC pads its last frame with silence, which would otherwise leave a gap).

export const AUDIO_FILES = {
  "bar-music": { seconds: 86.4000, loop: true },
  "cannonball": { seconds: 2.5703, loop: false },
  "clink-cheers": { seconds: 1.5446, loop: false },
  "dolphin-splash": { seconds: 3.0000, loop: false },
  "fold-close": { seconds: 0.1259, loop: false },
  "fold-open": { seconds: 0.4112, loop: false },
  "gull-1": { seconds: 2.9055, loop: false },
  "gull-2": { seconds: 3.0000, loop: false },
  "gull-3": { seconds: 2.9873, loop: false },
  "gull-4": { seconds: 1.8260, loop: false },
  "heli-approach": { seconds: 13.9005, loop: false },
  "heli-idle": { seconds: 9.4993, loop: true },
  "heli-rotor": { seconds: 7.4998, loop: true },
  "heli-takeoff": { seconds: 10.0000, loop: false },
  "hot-tub": { seconds: 10.9987, loop: true },
  "ice-glass": { seconds: 2.0734, loop: false },
  "landed-chime": { seconds: 1.1735, loop: false },
  "murmur": { seconds: 18.4985, loop: true },
  "night": { seconds: 18.4985, loop: true },
  "ocean": { seconds: 18.4985, loop: true },
  "package-thump": { seconds: 1.2000, loop: false },
  "phone-buzz": { seconds: 1.1775, loop: false },
  "pool-swim": { seconds: 10.9987, loop: true },
  "send-tick": { seconds: 0.2715, loop: false },
  "server-hum": { seconds: 18.4985, loop: true },
  "step-1": { seconds: 0.2854, loop: false },
  "step-2": { seconds: 0.3606, loop: false },
  "step-3": { seconds: 0.3105, loop: false },
  "typing": { seconds: 11.6869, loop: true },
  "wind": { seconds: 18.4985, loop: true },
} as const;

export type AudioFile = keyof typeof AUDIO_FILES;
